[theme]
primaryColor = "#7030A0"      # Systematik Purple
backgroundColor = "#F3F3F3"   # Main Background (Gray)
secondaryBackgroundColor = "#F3F3F3" # Sidebar & Inputs (Now matches Main Background)
textColor = "#1A1A1A"         # Dark Text
font = "sans serif"           
base = "light"
